= Changelog

== Changes in future versions
Any changes listed here will be incorporated into the next future release

.Additions
* *ProxAllium now directly communicates with Tor*. This means Tor is handled properly and opens up more possibilities!
* Support for bridges with pluggable transports `obfs` (all versions) and `scramblesuit`, GUI included for configuration
* Support for HTTP tunnel
* Added documentation for all INI options
* Added an option to start with Windows
* Added an option to start minimized
* Added an option to regenerate Tor configuration
* Added an option to switch to clean Tor circuits

.Fixed and changes
* Tor Output now resets after starting Tor instead of resetting everytime Tor stops or crashes
* Paths from configuration (`config.ini`) are no longer converted to absolute paths internally, this prevents use of absolute paths in the generated `torrc` file which may cause portability issues

== v0.3-beta (GUI Goodness)
Finally out of alpha! :)

.Additions
* **New GUI** with buttons, text fields, menubar, status indicator etc.
* Added "Hostname"
* Added Tray Tips (ProxAllium will notify you about Tor)
* Added multi-instance detection (ProxAllium will detect if it is already running)

.Fixes and changes
* Closing the Tor Output window will no longer prompt to stop Tor
* AsciiDoc is used instead of Markdown
* Fixed crashing if Tor was not initialized properly
* Tor is handled better internally (ProxAllium can detect crashes now)
* `config.ini` uses relative paths instead of absolute paths which can cause problems in a portable environment (Fixes https://github.com/DcodingTheWeb/ProxAllium/issues/1[#1])
* UPX is no longer used to compile ProxAllium, this should reduce anti-virus false positives.
* More minor internal changes

.Changes independent of ProxAllium's code
* New website with documentation, screenshots, webchat etc!

== v0.2-alpha (Featury Feast)
.Additions
* `ProxAllium.exe` now has its Product Version property filled
* Added ability to show Error/Warning messages made by Tor
* Added ability to Stop/Start Tor without restarting ProxAllium!
* Added ability to auto-generate `config.ini` (Therefore there is no need to pack `config.ini` in the release packages)
* Added support for HTTP(S) and SOCKS4/5 proxies (No GUI yet to configure these though)

.Fixes and changes
* **Fixed a lot of bugs** (including the bug where ProxAllium was not stopping Tor when exiting)
* **Optimisation and cleanup**
* Updated `README.md` and `CREDITS.md`
* Changed the internal structure/workings/design of ProxAllium
* Changed some text to be more meaningful
* Changed Tor's data directories location (You can now delete the `data` directory in `Tor/data` if you are upgrading)
* Tor Output Window no longer asks for confirmation if Tor has already exited
* ProxAllium no longer prompts to exit after closing Tor

(You can also https://github.com/DcodingTheWeb/ProxAllium/compare/v0.1-alpha...v0.2-alpha[view] the complete code changes across the previous release if you want)

**EDIT (23-02-2017)**: Added PGP signature to the list of downloads, you can find Dcoding The Web's public key https://dcodingtheweb.com/key.asc[here].
