= Documentation for ProxAllium
:doctype: book
:nofooter:
:toc: left

== Introduction
ProxAllium is a Free and Open Source front-end for Tor which makes it *easier* for normal everyday people to make more out of Tor!
With ProxAllium, you can circumvent censorship and be secure while using public internet hotspots (you can also be anonymous but only upto some extent).

Just run ProxAllium and now you have a working Tor circuit for you to use!

You can consult to the <<FAQ>> for more information.

== Installation
ProxAllium is fully portable, it does not require any _setup_ to be done and it does not mess with anything outside its own folder!

Just use any file archiver (http://7-zip.org/[7-zip] is recommended) to extract the `.7z` file onto your computer, you can extract it to anywhere, it is your choice.
The `7z` archive/package contains a folder called `ProxAllium` and within it, you can find ProxAllium itself and other necessary files.

Now you can start using ProxAllium by executing `ProxAllium.exe`! Easy, isn't it?

== Mailing List (Email Updates)
Now you can get e-mail notifications for new releases and updates from https://listengine.tuxfamily.org/proxallium.tuxfamily.org/news/[ProxAllium's Mailing List]!

=== Subscribing
To subscribe, send a mail with `subscribe` as the subject to `news-request@proxallium.tuxfamily.org`, then reply to the confirmation mail sent by `listmaster@tuxfamily.org`. If for some reason you are not able to subscribe, you can https://github.com/DcodingTheWeb/ProxAllium/wiki/FAQ#i-have-a-question-where-can-i-ask[contact me] asking to add your e-mail to the mailing list... I won't bite by the way!

=== Precautions and Information
. Your Email is **private** and is **not distributed** to anyone!
. You will receive emails updates from `mailman@proxallium.tuxfamily.org`, so make sure that it is in your whitelist/address book/contacts. You don't want to find those important notifications in your spam folder!
. **Do no reply to email notifications**! They will not reach anyone, the mailing list only accepts emails from administrators
. To unsubscribe, just follow the same procedure as <<Subscribing>> except use `unsubscribe` as the subject of the email


== FAQ
=== What does it do?
ProxAllium's goal is to make using https://www.torproject.org/about/overview.html.en[Tor] (Not to be confused with https://www.torproject.org/projects/torbrowser.html.en[Tor Browser]) easier for normal everyday users. It's basically a front-end for Tor, except that it tries to be more than that.

=== How is it different from Tor Browser (Bundle)?
It is not a replacement for the `TBB`, ProxAllium does not come with any browser! You should configure your own browser to work with `Tor`. Don't worry because it's really easy! You just have to use the proxy created by `Tor`. The method for using the proxy created by Tor is the same as using a traditional  https://en.wikipedia.org/wiki/SOCKS[SOCKS proxy].

=== Where do I download ProxAllium?
You can find the 7-zip packages at the https://github.com/DcodingTheWeb/ProxAllium/releases[Releases] page.

=== How do I make it start on startup?
Create a shortcut of `ProxAllium.exe` at `%appdata%\Microsoft\Windows\Start Menu\Programs\Startup` and Windows will start ProxAllium automatically on startup.

=== I have a question, where can I ask?
You can ask your questions at irc://chat.freenode.net/#DTW[#DTW in freenode] (https://kiwiirc.com/client/chat.freenode.net:+7000/?nick=ProxAlliumGuest?#DTW[Webchat is available too!]).

== Credits & Acknowledgments
=== Programming Language
Thanks to https://github.com/jonathanbennett73[Jonathan Bennett] & AutoIt Team for creating a wonderful scripting language called AutoIt! All of ProxAllium's code is 100% pure http://www.autoitscript.com/autoit3/[AutoIt].

=== Tor
Thanks to https://en.wikipedia.org/wiki/The_Tor_Project,_Inc[The Tor Project] for creating a wonderful thing called https://www.torproject.org/[Tor]. Tor enables millions of people to be anonymous and circumvent censorship!

=== ProxAllium's Icon
The icon for ProxAllium is a combined effort from many talented graphic artists... that excludes me.

* Onion Icon made by http://www.flaticon.com/authors/roundicons[Roundicons] from www.flaticon.com
* Computer Icon made by http://www.flaticon.com/authors/madebyoliver[Madebyoliver] from www.flaticon.com
* World Server Icon made by http://www.flaticon.com/authors/prosymbols[Prosymbols] from www.flaticon.com
* Double Headed Arrow Icon made by http://www.flaticon.com/authors/freepik[Freepik] from www.flaticon.com

All of these icons were compiled into one by me.

https://www.icoconverter.com/ was used to create the final `ico` file!


=== Infrastructure
Thanks to https://github.com[GitHub] (Code and Issue Tracker Hosting), https://www.tuxfamily.org/[Tux Family] (https://www.tuxfamily.org/en/about[Whole array of services to FOSS projects]) and https://freenode.net/[freenode] (IRC Network) for providing such generous services!

=== You!
For using ProxAllium!
